
[core]
name: hermit
displayText: Hermit
displayDescription: -Oculian Heavy crowd controll hover\n-Armed with dual plasma cannons to destroy crowds\n-big area of effect damage\n-Land attack\n-Strong shield, Regens shield quickly out of combat \n-2x Medusa(215 DPS 200 Range)
class: CustomUnitMetadata
price: credits=4200,crystal=185
maxHp: 500
maxShield: 1500
armour:5
shieldRegen: 0.1
mass: 3000
techLevel: 3
buildSpeed: 35s
radius: 30
isBio: false
softCollisionOnAll: 2
fogOfWarSightRange: 15

copyFrom: ROOT:Templates/customEffects.template

[graphics]
#lock_body_rotation_with_main_turret:true
total_frames: 1
image: hermit.png
image_wreak: hermit_wreck.png
image_turret: ROOT:\shared\graphics\medusa_barrel.png
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
dustEffect: true
teamColorsOnTurret: true



[attack]
turretRotateWithBody: true
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 240
shootDelay: 1s
isFixedFiring:true
turretMultiTargeting:true


[turret_barrel1]
x: 12
y: 6
projectile: 1
attachedTo:1
slave:true
shoot_sound: ROOT:sounds\Oculian_Armada\medusa_fire.wav
shoot_sound_vol: 0.6
barrelY: 35
recoilOffset: -8
recoilReturnTime: 0.7s
warmup: 0.30s
canAttackMaxAngle:35

chargeEffectImage:ROOT:shared\graphics\medusa_charge.png
warmupStartEffect:CUSTOM:noise
shoot_light:#f200ff
shoot_flame:CUSTOM:bigPlasmaFire

[turret_barrel2]
x: -12
y: 6
projectile: 1
attachedTo:1
slave:true
shoot_sound: ROOT:sounds\Oculian_Armada\medusa_fire.wav
shoot_sound_vol: 0.6
barrelY: 35
recoilOffset: -8
recoilReturnTime: 0.7s
warmup: 0.30s
linkDelayWithTurret:barrel1
canAttackMaxAngle:35

chargeEffectImage:ROOT:shared\graphics\medusa_charge.png
warmupStartEffect:CUSTOM:noise
shoot_light:#f200ff
shoot_flame:CUSTOM:bigPlasmaFire

[turret_1]
x: 0
y: 0
idleDir:0
canShoot: false
turnSpeed: 3.0
projectile: 1
image:hermit_cover.png

[effect_noise]
life: 200
alpha: 0.6
alsoPlaySound:ROOT:sounds\Oculian_Armada\medusa_charge.wav:0.6

[projectile_1]
targetGround:true
directDamage: 10
areaDamage:140
areaRadius:100
life: 300
speed: 8.0
drawSize: 2.5
color: #ffffff
lightColor: #ff0000
lightSize: 1.5
targetGroundSpread:20
explodeEffect:CUSTOM:medusa_explosion

[hiddenAction_shieldRegenOn]
autoTrigger:if not self.hasTakenDamage(withinSeconds=10) 
setUnitStats:shieldRegen=0.5
[hiddenAction_shieldRegenOff]
autoTrigger:if self.hasTakenDamage(withinSeconds=10)
setUnitStats:shieldRegen=0.1

[movement]
movementType: HOVER
targetHeight: 6
targetHeightDrift: 1.5
moveSpeed: 1.10
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.04
maxTurnSpeed: 3.0
moveSlidingMode :true
moveIgnoringBody:true
reverseSpeedPercentage:0.9