[core]
name: fg_grounder
class: CustomUnitMetadata
price: 1000
maxHp: 500
mass: 14000

displayText: Grounder
displayDescription: -Fulgorian Lightning Hovertank\n-Shield penetration, reduced building damage \n-Long warmup powerfull thunder cannon \n-Air and Land attack

techLevel: 1
buildSpeed: 16s
#availableInDemo: true

radius: 15
displayRadius: 15

isBio: false

fogOfWarSightRange: 14

[graphics]


image:        grounder.png
image_wreak:  grounder_wreck.png
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:2


lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 4

isFixedFiring: true

maxAttackRange: 200
shootDelay: 100

[turret_1]
x: 0
y: 0
projectile: 1
turnSpeedAcceleration: 1.0

shoot_sound:ROOT:sounds\grounder_fire.wav
shoot_sound_vol:0.7
shoot_flame: CUSTOM:sparks2*3, CUSTOM:light
shoot_light: #FFcceeee
chargeEffectImage:grounder_glow.png

recoilOffset: -5
recoilOutTime: 10
recoilReturnTime: 20
canAttackMaxAngle:15
warmupCallDownRate:0.3
warmup:60

[projectile_1]
directDamage: 85
shieldDamageMultiplier:1.25
shieldDefectionMultiplier:0
buildingDamageMultiplier:0.25

life: 25
instant: true
lightingEffect: true
largeHitEffect: true

lightColor: #ccffff
lightSize: 0.55

explodeEffect: CUSTOM:projectilePassThough, CUSTOM:lightningShock, CUSTOM:sparks*8, CUSTOM:hitLightFlash
explodeEffectOnShield: CUSTOM:lightningShock*1, CUSTOM:hitLightFlash

lightCastOnGround: true

[effect_sparks]
attachedToUnit: false
life: 60
physics: true
fadeOut: true
spawnChance: 0.5
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: SHARED:spark.png
priority: verylow

[effect_sparks2]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
image: SHARED:spark.png
priority: verylow

[effect_hitLightFlash]
priority: high
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
color: #ccffff
#color: #63e6e8
scaleFrom: 0.1
scaleTo: 0.1
alpha: 2
drawUnderUnits: false

[effect_light]
priority: high
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
color: #ccffff
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.6
drawUnderUnits: true

[effect_lightningShock]
life: 60
hOffset: 0
dirOffset: 0
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
scaleFrom: 1
scaleTo: 1
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.6

[effect_lightSlowFade]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #63e6e8
scaleFrom: 0.7
scaleTo: 0.7
alpha: 0.5
drawUnderUnits:true

[effect_projectileTrail]
image: SHARED:light_50.png
life: 12
fadeOut: true
attachedToUnit: false
color: #ccffff
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.4
drawUnderUnits:true
#ySpeedRelative:-1

[effect_projectilePassThough]
priority:high
frameIndex: 4
stripIndex: projectiles2
life: 20
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1
scaleTo: 0.5
alpha: 1
drawUnderUnits:false
ySpeedRelative:2
atmospheric: true

[movement]
movementType: HOVER
moveSpeed: 0.9
moveAccelerationSpeed: 0.025
moveDecelerationSpeed: 0.045

targetHeight:5
targetHeightDrift:1

reverseSpeedPercentage: 0.85

maxTurnSpeed: 3

moveSlidingMode :true
moveIgnoringBody:true





