[core]
name: demoCharge
class: CustomUnitMetadata
maxHp: 300
price: 1000
mass: 1000

displayText: Demo-charge
displayDescription: -Camoflauged Demolition charge designed to destroy buildings and large amounts of units(1000 damage, 2x building damage)\n-Does not detonate if destroyed\n-Is manually detonated remotely\ n-n-friendly fire, take cover.\n-kaboom

displayText_ru: Заряд Взрывчатки
displayDescription_ru: -Камуфлированная Бомба предназначенная для уничтожения строений и большого количества юнитов. (1000 Урона, x2 урон по зданиям)\n-Не взрывается если уничтожена\n-Активируется вручную дистанционно\n-Имеет огинь по своим, в укрытие.\n-Кабум

radius: 20
displayRadius:20

footprint: 0,0,0,0
constructionFootprint: 0,0,0,0

buildingToFootprintOffsetX:10
buildingToFootprintOffsetY:9

buildSpeed:20s

isBuilding: true
explodeTypeOnDeath: building

fogOfWarSightRange: 8

[hiddenAction_uncloak]
#decloaking via radar
autoTrigger: if self.numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=300, withTag='radar')
convertTo: demoCharge_visible

[graphics]
imageScale:0.8
isVisibleToEnemies:false
image: demo_charge.png
image_wreak: NONE

image_shadow: auto
shadowOffsetX:1
shadowOffsetY:1

[action_trigger]
text:Detonate
text_ru:Взорвать
fireTurretXAtGround:1
fireTurretXAtGround_withTarget:self
buildSpeed:1s
[turret_1]
x:0
y:0
canShoot:false
projectile:1

[projectile_1]
life:10
speed:10
instant:true
targetGround:true
friendlyFire:true
buildingDamageMultiplier:2
areaDamage:1000
areaRadius:100
largeHitEffect:true
[attack]
canAttack: false
maxAttackRange:125

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
targetHeight: -2

maxTurnSpeed: 0
turnAcceleration: 0.1