[core]
copyFrom:demo_charge.ini
name:demoCharge_visible
showInEditor:false
[hiddenAction_uncloak]
#decloaking via radar
autoTrigger: if not self.numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=300, withTag='radar')
convertTo: demoCharge

[graphics]
isVisibleToEnemies:true

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
targetHeight: 1

maxTurnSpeed: 0
turnAcceleration: 0.1