[core]
name:radar_ocua
tags:radar
class:customUnitMetadata
maxHp:500
price:600
mass:1000
radius:10
isBuilding:true

displayText: Radar
displayDescription:-Radar tower to see the enemy\n-Can see mines and cloaked units

displayText_ru: Радар
displayDescription_ru:-Башня с радаром для того что-бы видеть врага\n-Может видить мины и замаскированных юнитов

techLevel: 1
buildSpeed: 10.0s


buildingToFootprintOffsetX:0
buildingToFootprintOffsetY:-10

#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,0,0
#used for placement, and placement of other buildings
constructionFootprint:-1,-1,0,0

isBio: false

fogOfWarSightRange: 22

[graphics]
total_frames:6

animation_idle_start: 1
animation_idle_end: 5
animation_idle_speed: 6

image:ocua_radar.png
image_wreak:ocua_radar_destroyed.png
image_shadow: AUTO
shadowOffsetX:3
shadowOffsetY:1

[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false

[turret_uncloakrange]
x: 0
y: 0
limitingRange:200
invisible:true
projectile:dummy

[projectile_dummy]
instant: false
life: 1
speed: 1
directDamage: 0
areaDamage: 0
areaRadius: 0


largeHitEffect: false
explodeEffect: NONE
hitSound: false
invisible: true
trailEffect: false

[hiddenAction_starfield]
autoTrigger: if int(self.TimeAlive() % 4) == 1
spawnEffects: CUSTOM:starfield
[effect_starfield]
priority:critical
spawnChance: 1
image: layer_sarfield.png
createWhenOverLiquid: true
liveAfterAttachedDies: true
life: 420
scaleFrom: 0.8
scaleTo: 0.8
fadeInTime:30
fadeOut: true
attachedToUnit: true
#alpha:0.5
drawUnderUnits:false
shadow:false
yOffsetAbsolute:-25
xSpeedAbsoluteRandom:0.1
ySpeedAbsoluteRandom:0.1
dirOffsetRandom:90

[movement]
movementType:NONE

[ai]
lowPriorityTargetForOtherUnits:true